django-dashboard-black-master/app/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views

urlpatterns = [

    # The home page
    path('', views.index2, name='home'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

django-dashboard-black-master/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include('tracker.urls')),
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls")),             # UI Kits Html files
    
]

django-dashboard-black-master/tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker' #adds a namespace

urlpatterns = [
    #path('', views.test_static, name="static-test"),
    path('list_tests/', views.list_tests, name="list_tests"),
    path('list-tests/', views.list_tests2, name="list-tests"),
    path('download_template/', views.download_template, name='download_template'),
    path('upload/', views.upload_file, name='upload_file'),
]

django-dashboard-black-master/tracker/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from datetime import datetime, timedelta, timezone
from enum import Enum

# Create your models here.

class Test(models.Model):
    date = models.DateTimeField('date test taken')
    is_positive = models.BooleanField(blank=False)
    person = models.ForeignKey('person', on_delete=models.CASCADE, blank=True, null=True)

class Day(Enum):
    MONDAY = "Monday"
    TUESDAY = "Tuesday"
    WEDNESDAY = "Wednesday"
    THURSDAY = "Thursday"
    FRIDAY = "Friday"  

class CourseDateTime(models.Model):
    course = models.ForeignKey('Course', on_delete=models.CASCADE,)
    day = models.CharField(max_length=200, choices=[(tag, tag.value) for tag in Day], blank=True)
    time = models.TimeField(blank=True)
    
class Course(models.Model):
    title = models.CharField(max_length=200, blank=True)
    professor = models.CharField(max_length=200, blank=True)
    Section = models.CharField(max_length=200, blank=True)

class Person(models.Model):
    user = models.OneToOneField(User, related_name='person', on_delete=models.CASCADE, blank=True) # can now access user account easily, such as request.user.account.date
    def is_infected(self):
        test_date = None
        if len(self.test_set.filter(is_positive=True).order_by('-date')) == 0: #get most recent positive test)
            return False
        test_date = self.test_set.filter(is_positive=True).order_by('-date')[0].date #get most recent positive test
        delta = timedelta(weeks=3)
        now = datetime.now(timezone(timedelta(hours=-5)))
        return now - test_date < delta
class Dorm(Enum):
    ARMSTRONG = "Armstrong"
    BROWN = "Brown"
    # CALDWELL = "Caldwell", _("Caldwell")
    # CENTER_STREET_NORTH = "Center Street North", _("Center Street North")
    # CENTER_STREET_SOUTH = "Center Street South", _("Center Street South")
    CLOUDMAN = "Cloudman"
    # EIGHTH_STREET_EAST = "Eighth Street East", _("Eighth Street East")
    # EIGHTH_STREET_SOUTH = "Eighth Street South", _("Eighth Street South")
    # EIGHTH_STREET_WEST = "Eighth Street West", _("Eighth Street West")
    # FIELD = "Field", _("Field")
    # FITTEN = "Fitten", _("Fitten")
    # FOLK = "Folk", _("Folk")
    # FREEMAN = "Freeman", _("Freeman")
    # FULMER = "Fulmer", _("Fulmer")
    # GLENN = "Glenn", _("Glenn")
    # GOLDIN_HOUSE = "Goldin House", _("Goldin House")
    # GRADUATE_LIVING_CENTER = "Graduate Living Center", _("Graduate Living Center")
    # GRAY_HOUSE = "Gray House", _("Gray House")
    # HANSON = "Hanson", _("Hanson")
    # HARRIS = "Harris", _("Harris")
    # HARRISON = "Harrison", _("Harrison")
    # HAYES_HOUSE = "Hayes House", _("Hayes House")
    # HEFNER = "Hefner", _("Hefner")
    # HOWELL = "Howell", _("Howell")
    # MATHESON = "Matheson", _("Matheson")
    # MAULDING = "Maulding", _("Maulding")
    # MONTAG = "Montag", _("Montag")
    # NELSON_SHELL = "Nelson Shell", _("Nelson Shell")
    # NORTH_AVENUE_EAST = "North Avenue East", _("North Avenue East")
    # NORTH_AVENUE_NORTH = "North Avenue North", _("North Avenue North")
    # NORTH_AVENUE_SOUTH = "North Avenue South", _("North Avenue South")
    # NORTH_AVENUE_WEST = "North Avenue West", _("North Avenue West")
    # PERRY = "Perry", _("Perry")
    # SMITH = "Smith", _("Smith")
    # STEIN_HOUSE = "Stein House", _("Stein House")
    # TENTH_AND_HOME_BLDG_A = "Tenth and Home Bldg A", _("Tenth and Home Bldg A")
    # TENTH_AND_HOME_BLDG_B = "Tenth and Home Bldg B", _("Tenth and Home Bldg B")
    # TENTH_AND_HOME_BLDG_C = "Tenth and Home Bldg C", _("Tenth and Home Bldg C")
    # TENTH_AND_HOME_BLDG_D = "Tenth and Home Bldg D", _("Tenth and Home Bldg D")
    # TENTH_AND_HOME_BLDG_F = "Tenth and Home Bldg E", _("Tenth and Home Bldg E")
    # TENTH_AND_HOME_BLDG_G = "Tenth and Home Bldg F", _("Tenth and Home Bldg F")
    # TOWERS = "Towers", _("Towers")
    # WOODRUFF_NORTH = "Woodruff North", _("Woodruff North")
    # WOODRUFF_SOUTH = "Woodruff South", _("Woodruff South")
    # ZBAR = "Zbar", _("Zbar")
class Student(models.Model):
    person = models.OneToOneField(Person, related_name='student', on_delete=models.CASCADE, blank=True, null=True)
    course_schedule = models.ManyToManyField(Course, related_name='course_schedule', blank=True)
    
    dorm = models.CharField(max_length=200, choices=[(tag, tag.value) for tag in Dorm], blank=True)
        
class Building(Enum):
    SPRING_STREET = "760 Spring Street"
    # ALLEN = "Allen Sustainable Eduation Building", _("Allen Sustainable Eduation Building")
    # BOGGS = "Boggs Building", _("Boggs Building")
    # BUNGER_HENRY = "Bunger Henry Building", _("Bunger Henry Building")
    # CHERRY_EMERSON = "Cherry Emerson Building", _("Cherry Emerson Building")
    CULC = "Clough Undergraduate Learning Commons"
    # COC = "College of Computing", _("College of Computing")
    # GUGGENHEIM = "GUGGENHEIM AEROSPACE BUILDING", _("GUGGENHEIM AEROSPACE BUILDING")
    # ENGINEERING = "ENGINEERING SCIENCE & MECHANICS", _("ENGINEERING SCIENCE & MECHANICS")
    # HOWEY = "HOWEY PHYSICS BUILDING", _("HOWEY PHYSICS BUILDING")
    # IC = "INSTRUCTIONAL CENTER", _("INSTRUCTIONAL CENTER")
    # KENDEDA = "KENDEDA BUILDING FOR INNOVATIVE SUSTAINABLE DESIGN", _("KENDEDA BUILDING FOR INNOVATIVE SUSTAINABLE DESIGN")
    # LOVE = "LOVE MANUFACTURING BLDG (MRDC II)", _("LOVE MANUFACTURING BLDG (MRDC II)")
    # MASON = "MASON", _("MASON") 
    # MSE = "MSE", _("MSE")
    # PAPER = "PAPER TRI", _("PAPER TRI") 
    # SCHELLER = "SCHELLER", _("SCHELLER")
    # SKILES = "SKILES", _("SKILES") 
    # SMITH = "SMITH", _("SMITH")
    # SWANN = "SWANN", _("SWANN") 
    # VAN_LEER = "VAN_LEER", _("VAN_LEER")
    # WEBER = "WEBER", _("WEBER") 
    WEST_VILLAGE = "WEST vILLAGE DINING COMMONS"
    # WHITAKER = "WHITAKER", _("WHITAKER")
class Employee(models.Model):
    person = models.OneToOneField(Person, related_name='employee', on_delete=models.CASCADE, blank=True, null=True)
    workplace = models.CharField(max_length=200, choices=[(tag, tag.value) for tag in Building], blank=True)

class FriendGroup(models.Model):
    friends = models.ManyToManyField(User, related_name='friend_group', blank=True)

django-dashboard-black-master/tracker/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

django-dashboard-black-master/tracker/views.py
from django.shortcuts import render
from .models import *
from datetime import datetime, timedelta, timezone
from django.contrib.auth.decorators import login_required
import pandas as pd

from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import UploadFileForm
from django.urls import reverse

# Create your views here.
def test_static(request):
     _file = open('static/tracker/wrapper.html').read()
     return render(request, 'tracker/test_static.html', {"HtmlFile": _file})
@login_required
def list_tests(request):
    #_list = Test.objects.filter(date__gte=datetime.now(timezone(timedelta(hours=-5)))-timedelta(weeks=3))
#     _list = Test.objects.all()
     _list = [] 
#     person_tests = request.user.person.test_set.order_by('-date')
#     _list = Test.objects.filter(date__gte=datetime.now(timezone(timedelta(hours=-5)))-timedelta(weeks=52)).order_by('-date')
     return render(request, 'tracker/list_tests.html', {"test_list": _list,})
#     return render(request, 'tracker/list_tests.html', {"test_list": _list, "user_tests": person_tests})
def download_template(request):
     df = pd.DataFrame(data=[], columns=["id", "date/time", "is positive"])
     df.to_excel("user_data.xlsx")
     with open("user_data.xlsx", 'rb') as fh:
          response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
          response['Content-Disposition'] = 'inline; filename=' + "user_data.xlsx"
          return response




def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if not form.is_valid():
          #   handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect(reverse('tracker:list-tests'))
    else:
        form = UploadFileForm()
    return render(request, 'tracker/upload.html', {'form': form})


def list_tests2(request):
     _list = Test.objects.all()
#     person_tests = request.user.person.test_set.order_by('-date')
#     _list = Test.objects.filter(date__gte=datetime.now(timezone(timedelta(hours=-5)))-timedelta(weeks=52)).order_by('-date')
     
     if request.POST.get('filter', False) == 'user_data':
          _list = request.user.person.test_set.order_by('-date')
     if request.POST.get('filter', False) == 'only_positive':
          _list = Test.objects.filter(is_positive=True).order_by('-date')
     if request.POST.get('filter', False) == 'last_month':
          _list = Test.objects.filter(date__gte=datetime.now(timezone(timedelta(hours=-5)))-timedelta(weeks=52)).order_by('-date')
     if request.POST.get('filter', False) == 'friend_group':
          _list = request.user.person.test_set.order_by('-date')
          if len(request.user.friend_group.all()) != 0:
               for friend in request.user.friend_group.all()[0].friends.all():
                    _list |= friend.person.test_set.order_by('-date')
     
     return render(request, 'tracker/list_tests.html', {"test_list": _list,})
#     return render(request, 'tracker/list_tests.html', {"test_list": _list, "user_tests": person_tests})





# def handle_uploaded_file(f):
#      df = pd.read_excel(open(f, 'rb'))

#     with open('some/file/name.txt', 'wb+') as destination:
#         for chunk in f.chunks():
#             destination.write(chunk)

django-dashboard-black-master/core/templates/tracker/list_tests.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
{%block upload%}{%endblock%}
<br>
<div class="card">
  <div class="card-body">
    <form action="{% url 'tracker:list-tests' %}" method="post">
    {% csrf_token %}
      <div class="form-group">
        <label for="filter">Filter your data</label>
        <select class="form-control" name="filter" id="exampleFormControlSelect1">
        {% comment %} <select name="filter" id="filter"> {% endcomment %}
        <option value="user_data">Only your tests</option>
        <option value="only_positive">Only positive tests</option>
        <option value="last_month">last 30 days</option>
        <option value="friend_group">Friend Group tests</option>
        </select>
        <input type="submit" value="Submit Changes">
      </div>
    </select>
    </form>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="card ">
      <div class="card-header">
        <h4 class="card-title"> Simple Table</h4>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table tablesorter " id="">
            <thead class=" text-primary">
              <tr>
                <th>Date</th>
                <th>Position</th>
                <th>Result</th>
                <th>Infectious<th>
              </tr>
            </thead>
            <tbody>
              {% comment %} <td>Student</td>
              <td>Student</td>
              <td>Student</td>
              <td>Student</td> {% endcomment %}
              {% for test in test_list %}
                <td>{{test.date}}</td>
                {% if test.person.student %}
                    <td>Student</td>
                {%else %}
                    <td>Employee</td>
                {% endif %}
                {% if test.is_positive %}
                    <td>Positive</td>
                {%else %}
                    <td>Negative</td>
                {% endif %}
                {% if test.person.is_infected %}
                    <td>Infectious</td>
                {%else %}
                    <td>Not Infectious</td>
                {% endif %}
                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <button class="btn btn-primary animation-on-hover" type="button">Download Template</button>
  </div>
<!--<a href="{%url 'tracker:download_template' %} " download> Download template</a><br>-->
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

django-dashboard-black-master/core/templates/tracker/test_static.html
{% load static %}
<img src="{% static 'tracker/test.jpg' %}" alt="My image">
{{HtmlFile|safe}}

django-dashboard-black-master/core/templates/tracker/upload.html
{% extends 'list_tests.html' %}

{% load static %}

{% block upload %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile" class="file" style="color:#FFFFFF">
    <button type="submit" class="btn btn-success animation-on-hover">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

{% endblock %}